### ISSUE TITLE
ExistingAttributesPersistence model collisions

### ISSUE THREAD

**Issue by xire28** [phurni/mortimer-poignant#4]
All models use `$ExistingAttributesPersistence_tableColumns` defined as class variable in Mortimer\Poignant\Model to store their existing column names. When the model `eloquent.saving` event handler tries to access the variable later, `$ExistingAttributesPersistence_tableColumns` contains the columns of the last model that called `bootExistingAttributesPersistence`.

As a result, `ExistingAttributesPersistence` trait deletes all model attributes in most cases.

**Comment by phurni** [comment]
Good catch! Thanx for the smart fix also.
